In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.13.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 3s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.5969918 , -0.46711442,  0.3582375 , -0.16129577, -0.28973994,
         0.2936043 ,  0.495485  ,  0.59082335, -0.49042195, -0.57375515]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.05411905, 0.06162476, 0.14066985, 0.08367015, 0.07358478,
        0.1318655 , 0.16136408, 0.17750548, 0.06020505, 0.05539133]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.0259728

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/5
1875/1875 [==============================] - 11s 5ms/step - loss: 0.2902 - accuracy: 0.9159
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1399 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1044 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0852 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0715 - accuracy: 0.9769
313/313 - 1s - loss: 0.0777 - accuracy: 0.9758 - 602ms/epoch - 2ms/step


[0.07768693566322327, 0.9757999777793884]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.9386425e-08, 5.4634334e-08, 6.8071004e-06, 6.9360613e-05,
        4.6100814e-11, 2.2415547e-09, 3.3439773e-14, 9.9991560e-01,
        4.0109853e-07, 7.6867182e-06],
       [2.6493099e-09, 2.9227097e-06, 9.9965250e-01, 3.4392593e-04,
        1.5726921e-15, 4.0243805e-07, 4.2255017e-09, 1.0108147e-12,
        2.8264307e-07, 1.2477390e-13],
       [5.2101001e-08, 9.9984634e-01, 7.0399210e-06, 2.7752749e-06,
        4.3532789e-05, 4.4513131e-06, 2.4734916e-06, 4.9963070e-05,
        4.3353110e-05, 1.1263835e-07],
       [9.9990249e-01, 1.0495643e-09, 7.1248578e-05, 3.1505749e-07,
        1.3762825e-06, 5.1759554e-07, 1.3162993e-05, 3.9971919e-06,
        9.5420436e-09, 6.7716778e-06],
       [2.7168326e-07, 1.1705981e-10, 3.9474716e-07, 5.0404498e-09,
        9.9868053e-01, 1.8027983e-07, 8.8878187e-07, 2.6864178e-05,
        2.1225752e-07, 1.2906500e-03]], dtype=float32)>